### ISSUE TITLE
Add restriction: Parameters required by a child workflow must be declared in the setup workflow

### ISSUE THREAD

**Issue by amarnus** [bufferings/orb-split-config#12]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Describe the problem imposed by not having this feature

If any of the child CircleCI config files have parameters defined, then they must also be declared in the setup workflow. Otherwise, a parametrised pipeline run will fail since CircleCI won't be able to recognise the parameters sent.

### Describe the solution you'd like

If this restriction can be verified, hope it can be added to the project `README`.

**Comment by bufferings** [comment]
Thank you! I will check it and add the sentence to README.

**Comment by bufferings** [comment]
I confirmed it and added it to the README. Thank you!
